### ISSUE TITLE
How to set Content-type=application/json in response

### ISSUE THREAD

**Issue by luigisaetta** [fnproject/fdk-python#37]
I've tried to produce as response a JSON object, but using FDK content-type is always set to text/plain

I have tried using:
(1) simply a dictionary

    res = {}
    # res['apps'] = vet
    res['id'] = 100

    return res

(2) using response.RawResponse
with:

return response.RawResponse(
        ctx,
        status_code=200, 
        headers=[{"Content-Type":"application/json"}], 
        response_data=res
    )

but Content-type is not set to application/json

**Comment by denismakogon** [comment]
Hi, you need to type in a lowercase header:
```python
def content_type(ctx, data=None):
    return response.RawResponse(
        ctx, response_data="OK",
        status_code=200,
        headers={"content-type": "application/json"}
    )
```
this should work for you

**Comment by luigisaetta** [comment]
Mmmmm... the content-type is set correctly, but then the body contains an error

{
    "error": {
        "message": "invalid json response from function err: json: cannot unmarshal string into Go struct field CallResponseHTTP.headers of type []string"
    }
}

To be clear, my def handler(ctx, data=None, loop=None) function ends exactly with this code:

return response.RawResponse(
        ctx,
        response_data="OK",
        status_code=200, 
        headers={"content-type":"application/json"}
    )

**Comment by denismakogon** [comment]
So, the temporary solution is:
```
headers={"content-type":["application/json",]}
```
I'll fix that in a newer FDK version.

**Comment by denismakogon** [comment]
I found an issue in headers rendering, thank you for pointing it out. PR is there, a newer version will be available soon.

**Comment by luigisaetta** [comment]
ok, great. NIce work

**Comment by mnasruul** [comment]
w
