### ISSUE TITLE
what about the cookies?

### ISSUE THREAD

**Issue by fmtovland** [fnproject/fdk-python#84]
So this is not a problem as such since python already supports cookies so well via it's own http module. Still I'm curious about their absence since headers are pretty well documented. Within the file context.py in the python fdk, I ran a text search for the word cookie. Nada. Cookies are sent via http headers, so getting them is as simple as 

from http.cookies import SimpleCookie
cookies=SimpleCookie(ctx.Headers().get("fn-http-h-cookie"))
(or something like that)

but how come it's not ctx.Cookies() or something? I would have thought they're a pretty common use case for a http api. that's how session information is generally stored after all. Was this a conscious design decision because not everyone uses them? Was it just forgotten or put on the back burner?

not complaining, like I said easy fix. Just curious.

**Comment by denismakogon** [comment]
Hi. Thanks for reporting this.
FYI, there are two type instances of the context: `InvokeContext` that represents a generic type of a function's invocation (could be triggered through http or mq or whatever), and `HTTPGateway` that represents the particular invocation via HTTP (only this type represents HTTP request).

FYI, context API is common through all FDKs we support officially, so, if there's a need to add `Cookie` method on the context, please open an issue against Fn repo.

**Comment by fmtovland** [comment]
@denismakogon I'll do just that. I'll also close the issue here because having the same issue open in two places is just confusing for anyone trying to fix the problem.
