### ISSUE TITLE
incorrect headers being sent

### ISSUE THREAD

**Issue by fmtovland** [fnproject/fdk-python#85]
**Description**

**Steps to reproduce the issue:**
1. start the fn server
2. create a blank project with fn init --runtime python --trigger http foo
3. cd foo
4. deploy the fresh project to the server with fn deploy --local --app foo --create-app
5. repeatedly run curl -i localhost:8080/t/foo/foo

**Describe the results you received:**
sometimes the Content-Type header will be application/json, as expected.
other times the Content-Type header will appear twice. once with text/plain and once with None.

**Describe the results you expected:**
the Content-Type should consistantly be application/json, as that's what the application manually sets it to

**Additional information you deem important (e.g. issue happens only occasionally):**
I ran this command 1000 times and counted the ratio of expected result to weird result (with a script don't worry, not crazy)
395 correct, 605 incorrect

**Output of `FDK version` (PIP output):**

```
not even sure how to check this, though in func.yaml it says schema_version: 20180708
```

**Additional environment details (python version, code sample, etc.):**
fn cli version 0.5.78
docker images:
fnproject/fnserver   latest              aad56d223cc2        3 weeks ago
fnproject/python     3.6                 c31b51a1f190        3 weeks ago
fnproject/python     3.6-dev             aa4e9945b65f        10 months ago

**Comment by denismakogon** [comment]
Can you please try with the latest code from the master of the FDK?

**Comment by rdallman** [comment]
that is a strange result, yeah, I think we've fixed it https://github.com/fnproject/fdk-python/pull/83 - we should have pip release up soon to try, too (with versions, too, to help with that issue :)

**Comment by fmtovland** [comment]
1000/1000 perfect score, good fix, job well done, sorry for reporting a bug litterally two hours after it gets fixed. look forward to it being pushed to pip. not fond of the manual way...

sorry I let this open for so long when it had already been fixed. I just got confused on how to build the images.

**Comment by rdallman** [comment]
no worries, thank you for reporting, sorry for the bugs. fix is pushed https://pypi.org/project/fdk/#history now, please let us know if any issues
