### ISSUE TITLE
'InvokeContext' object has no attribute '_InvokeContext__invoke_context

### ISSUE THREAD

**Issue by dkishenk** [fnproject/fdk-python#94]
Hi there

Seems `__invoke_context` is undefined as result fail to call `ctx.RequestURL()` and `ctx.Method()`

https://github.com/fnproject/fdk-python/blob/217bfe55514f142d193bfe9ae509e124eec9cf2a/fdk/context.py#L109

https://github.com/fnproject/fdk-python/blob/217bfe55514f142d193bfe9ae509e124eec9cf2a/fdk/context.py#L112

Thanks

**Comment by denismakogon** [comment]
Thanks for reporting, the corresponding PR was created. Expect a change to land on Monday, the next release version is `0.1.9`
