### ISSUE TITLE
shipping more than one .py file

### ISSUE THREAD

**Issue by jan-g** [fnproject/fdk-python#98]
**Description**

I'm not the only person who's tried to ship more than one .py module from the function directory.

We should add /function to the PYTHONPATH.

(While we are tweaking the Dockerfile, populating /python before /functions means there's less to re-push on a trivial change.)

**Comment by mrc** [comment]
hehe looks like you did the first part https://github.com/fnproject/cli/blame/ba48d8c47a76f9377f819f5d99d9cfdfa830ded9/langs/python.go#L126

and the second part is now in PR https://github.com/fnproject/cli/pull/613

**Comment by mrc** [comment]
Version 0.5.100 of the cli (just built now) generates a Dockerfile which populates & chmod's /python in the same layer, and the "final" layer is now just the customer's code, so there's less to re-push when the dependencies don't change. Resolving this comment now, feel free to reopen if I missed a spot.
